///展示类型  每个类型对应一个weight组件
const SHOWTYPE_BALL = "BALL";
const SHOWTYPE_BANNER = "BANNER";
const SHOWTYPE_HOMEPAGE_SLIDE_PLAYLIST = "HOMEPAGE_SLIDE_PLAYLIST";
const SHOWTYPE_HOMEPAGE_NEW_SONG_NEW_ALBUM = "HOMEPAGE_NEW_SONG_NEW_ALBUM";
const SHOWTYPE_SLIDE_SINGLE_SONG = "SLIDE_SINGLE_SONG";
const SHOWTYPE_SHUFFLE_MUSIC_CALENDAR = "SHUFFLE_MUSIC_CALENDAR";
const SHOWTYPE_HOMEPAGE_SLIDE_SONGLIST_ALIGN = "HOMEPAGE_SLIDE_SONGLIST_ALIGN";
const SHOWTYPE_SHUFFLE_MLOG = "SHUFFLE_MLOG";
const SHOWTYPE_SLIDE_VOICELIST = "SLIDE_VOICELIST";
const HOMEPAGE_SLIDE_PLAYABLE_MLOG = 'HOMEPAGE_SLIDE_PLAYABLE_MLOG';
const SHOWTYPE_SLIDE_PLAYABLE_DRAGON_BALL = "SLIDE_PLAYABLE_DRAGON_BALL";
const SLIDE_PLAYABLE_DRAGON_BALL_MORE_TAB =
    "SLIDE_PLAYABLE_DRAGON_BALL_MORE_TAB";
const SLIDE_RCMDLIKE_VOICELIST = 'SLIDE_RCMDLIKE_VOICELIST'; //热门播客
const HOMEPAGE_BLOCK_HOT_TOPIC = 'HOT_TOPIC'; //热门话题
const HOMEPAGE_SLIDE_PODCAST_VOICE_MORE_TAB = 'SLIDE_PODCAST_VOICE_MORE_TAB';
const HOMEPAGE_YUNCUN_PRODUCED = 'YUNCUN_PRODUCED'; //云村出品
const SLIDE_PLAYABLE_DRAGON_BALL_NEW_BROADCAST =
    'SLIDE_PLAYABLE_DRAGON_BALL_NEW_BROADCAST'; //广播