import 'package:paisa/localization/localization_keys.dart';

class Zh {
  Map<String, String> get messages => {
        LocalizationKeys.appTitle: "Paisa",
        LocalizationKeys.home: "首页",
        LocalizationKeys.transactions: "交易",
        LocalizationKeys.welcomeMessage: "欢迎回来!",
        LocalizationKeys.introTitle: "帮助您控制储蓄的简单方法",
        LocalizationKeys.intoSummary1: "使用我们的应用程序管理您的资金",
        LocalizationKeys.intoSummary2: "轻松跟踪费用，获得更好的预算",
        LocalizationKeys.intoSummary3: "随时随地掌控您的开支",
        LocalizationKeys.introCTA: "开始使用",
        LocalizationKeys.next: "下一步",
        LocalizationKeys.welcome: "嗨，欢迎来到",
        LocalizationKeys.welcomeDesc: "我们应该怎么称呼您",
        LocalizationKeys.image: "图片",
        LocalizationKeys.imageDesc: "让我们设定你的形象",
        LocalizationKeys.enterNameHint: "输入名称",
        LocalizationKeys.nameHint: "名字",
        LocalizationKeys.income: "收入",
        LocalizationKeys.categories: "类别",
        LocalizationKeys.done: "完成",
        LocalizationKeys.cancel: "取消",
        LocalizationKeys.addedCategories: "已添加的类别",
        LocalizationKeys.defaultCategories: "默认的类别",
        LocalizationKeys.accounts: "账户",
        LocalizationKeys.addedAccounts: "已添加的账户",
        LocalizationKeys.defaultAccounts: "默认的账户",
        LocalizationKeys.back: "上一步",
        LocalizationKeys.addAccount: "新增账户",
        LocalizationKeys.recommendedAccounts: "预设账户",
        LocalizationKeys.updateAccount: "更新账户",
        LocalizationKeys.addCategory: "新增类别",
        LocalizationKeys.recommendedCategories: "预设类别",
      };
}
